### PR TITLE
Added per biome tree replacement rate config

### PR DESCRIPTION
**Pull request by Elix-x**
Added per biome tree replacement rate config. Tried to respect code style as much as i could.
Populating biomes map in init phase is important, as we are sure that in init, all biomes have been registered. We are not for pre init.
Uses biomes registry and name mapping.
Default values not provided, but can be.

PS: I was too lazy to describe how to do this on MCF thread, so i coded it.

### CODE REVIEW

**Comment by WhiskyTangoFawks** [comment]
Intersting, I'll have a look at it a bit later this week when I have time,  and I am not on my phone , but just looking at it quickly I think there's a simpler way to do it.  However, because tree replacement isn't done randomly, modifying the replacement rate isn't going to solve the clumping issue with bop, it will just make it more rare. What actually will fix it is modifying the tree per chunk number when I get it from the biome.

**Comment by Elix-x** [comment]
`What actually will fix it is modifying the tree per chunk number when I get it from the biome.`

Can do.

**Comment by WhiskyTangoFawks** [comment]
If you want to have a go feel free, just be aware, if you haven't noticed, that how I am generating is very different from the standard vanilla method

**Comment by Elix-x** [comment]
I did not take a deep look at your code, but i know that it's very different anyway.
_I don't think vanilla gen allows to do what you do easily._

**Pull request closed without merging**
